### ISSUE TITLE
Flight Log End Timestamp

### ISSUE THREAD

**Issue by shane-williams-sky** [hrishiballal/flight-logging-protocol-development#10]
Is “logging end date/time” worth adding? For instance, if the tick is every 5 seconds and the flight controller or GCS actually ends its log recording 4 seconds after the last tick, the real end time will be a few seconds past the inferred one.

**Comment by hrishiballal** [comment]
Yes I have added two events in this and also a additional section for this. And a "landed" event in the GeoJSON as well.
