### ISSUE TITLE
Flight_Logging_Items -> battery_voltage or battery_power

### ISSUE THREAD

**Issue by shane-williams-sky** [hrishiballal/flight-logging-protocol-development#14]
In many common flight logs from various manufacturers, battery_power is given in addition to battery_voltage. For operational, safety, and compliance situations battery_power could be more useful as a flight logging item instead of battery_voltage.

By battery_power, we mean percentage of battery power remaining. Many operators specify that aircraft must land with at least a certain percentage remaining, i.e. 25%. Voltage remaining in the battery may not be useful unless the overall capacity is also stated.

**Comment by hrishiballal** [comment]
Hi @shane-williams-sky Thanks yes, it makes sense, there is nothing stopping from reporting voltage anyway since it can be declared, I have made the changes. Thanks!
