### ISSUE TITLE
Create Pre-Defined Message-Types values as it appears to be open ended

### ISSUE THREAD

**Issue by ghost** [hrishiballal/flight-logging-protocol-development#4]
The protocol has an example of "message_type": "flight_logging_submission", what are other options available?

**Comment by hrishiballal** [comment]
Hi @spolica, thank you for the comment. I have updated the document to add notes about this. Do you have suggestions or recommendations? The only thing that comes to my mind is if we want to use this protocol for "non-standard" logging. for e.g. if the drone detects critical failure e.g. battery power is low then we use could use it as a "critical_state_logging" as a message type. Let me know if you have other suggestions.

**Comment by ghost** [comment]
Hello there @hrishiballal, sorry about the delayed response. This could be extended to any industry standard protocol for flight notifications including but not limited to 'alerting.' However, this could also be interpreted as too granular. There's also component streaming of partial data that could point to specifics.

**Comment by hrishiballal** [comment]
Hi @spolica thanks for the note. I think that for the momemt we leave it at this, if need be we can pick this up with additional message-types. I do think that very shortly we will have to add new message types to the protocol.
