### ISSUE TITLE
Additional exchange type to illustrate a realtime flight

### ISSUE THREAD

**Issue by shane-williams-sky** [hrishiballal/flight-logging-protocol-development#5]
Should we add “flight_enroute” as an option to “exchange_type”? 
This would denote a flight that’s in progress.

**Comment by hrishiballal** [comment]
Hi @shane-williams-sky did you mean adding "flight_enroute" in the events? The events section is where all the flight events are logged.

**Comment by shane-williams-sky** [comment]
If a valid message_type could be 'flight_enroute' instead of 'flight_logging', a system that's reading the message would know to expect further updates to this message (i.e. realtime location updates). Perhaps this isn't the right way to flag it, but some way to flag that a flight is currently underway instead of a completed flight.

**Comment by hrishiballal** [comment]
Yes that is great idea, in this case though, we will still have two different logs correct the "flight_enroute" could be the public version and the "flight_logging" may or may not be exposed and be for internal company records.
