### ISSUE TITLE
“Public version” could obscure position for InterUSS publishing

### ISSUE THREAD

**Issue by shane-williams-sky** [hrishiballal/flight-logging-protocol-development#8]
Would it make sense to obfuscate actual position in the ‘public’ version of the flight log, similar to the Volume message in InterUSS. This could make integrating this protocol into an InterUSS message more straightforward. It would also be a good way to protect privacy of commercial operators.

**Comment by hrishiballal** [comment]
I think this is a great idea, my thinking was that that "flight_logging_geojson" is the "public" portion of the flight log and to submit it into InterUSS. The USS provider will need to read the flight log and can then just provide the x,y, zoom to InterUSS. I would like to discuss a bit more. GeoJSON ensures that it is kept standard and every operator can then obfuscate it on their side.

**Comment by shane-williams-sky** [comment]
I agree that GeoJSON is the way to go for public data. The thought is to obfuscate exact positions so that instead of having GPS coordinates to 7 decimal places, we only showed 3 decimal places in the 'public' version, it would result in accuracy within about 12 meters, which would protect privacy. Of course the GeoJSON could just be a polygon which would indicate operations within the bounds of that polygon.

**Comment by hrishiballal** [comment]
Yes agreed, GeoJSON recommends upto [six decimals](https://tools.ietf.org/html/draft-ietf-geojson-04#section-11.2), I will make the changes to the text.
